### ISSUE TITLE
[BUG] i was afking and on a platform i was some how knocked of and my death chest seemed to be really low instead of where i died

### ISSUE THREAD

**Issue by rockfpc** [theoutpostmc/issue-tracker#11]
**Describe the bug**
A clear and complete description of what the bug is.

**To Reproduce**
2. Do on '....'
3. Then '....'

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
Optional, but may help us solve your issue faster.

**Comment by thecenters** [comment]
Unfortunately this isn't something that can be fixed by me. The plugin isn't working properly and the creator needs to update it.
