### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tdsacco0122** [theoutpostmc/issue-tracker#15]
**Describe the bug**
When you add a stack of ore to a furnace it smelts some of it and leaves the rest our of existence. 

**To Reproduce**
1. Go to a furnace and put in 64 Coal and 64 Iron Ore
2. Do on vanilla plus 
3. Then wait a little bit for it to smelt. (I waited 45 min). Finally take out ingots and count.

**Expected behavior**
I expected it to smelt 64 ore but it ended up smelting only 14.

**Screenshots**

![image](https://user-images.githubusercontent.com/53389132/71941016-72d28780-3186-11ea-8009-ef32657fd75a.png)

**Comment by thecenters** [comment]
This was f ixed
