### ISSUE TITLE
[BUG] Player equipping 'horse armor' using /hat command gain its enchantment effect.

### ISSUE THREAD

**Issue by IHateChair** [theoutpostmc/issue-tracker#19]
**Describe the bug**
By equipping horse armor on helmet slot using /hat command, a player can gain enchantment effects such as feather falling. This might not be a game-breaking bug but possibly unintentional.

**To Reproduce**
1. Have any rank that are accessible to /hat command and be on V+
2. Hold any horse armor with enchantments that grant a defensive buff and use /hat

**Expected behavior**
The player with enchanted horse armor in the helmet slot is now granted with defensive buffs. This bug was tested only with feather falling enchantment.

**Comment by thecenters** [comment]
Unintentional, but I don't see anything too OP happening here. It adds value to the horse armor if nothing else. Thanks for reporting.
