### ISSUE TITLE
[BUG] Shulker box rearranging (Vanilla)

### ISSUE THREAD

**Issue by Androiddude73** [theoutpostmc/issue-tracker#2]
A clear and complete description of what the bug is:
I am struggling to figure out the cause of this, but I like to have my shulker boxes organized in specific ways, you can see an example with my gold box in the photos below. For some reason, when I pick the box up and place it back down, the arrangement of the items inside gets completely randomized. If I then pick the box up and place it back down again, it stays the way it is. This is also happening with my valuables box. I just tried testing it with another shulker I keep in my echest, again, photos below, i moved the heart of the sea to the right slot, picked it up and placed it back down, and it returned to the left slot. It looks like placing items in will keep them in the same spot, but at this point I'm not too sure.

**To Reproduce** (It doesn't seem like anyone else is having this problem but:)
1. Place items in whatever order in a shulker, and make sure there are open spaces for them to move around to
2. Close the shulker, break it and pick it up in your inventory.
3. Place it back down, look inside, and the contents should have shifted

**Expected behavior**
It should have completely rearranged where items are located between picking it up and placing it back down, and if you repeat the process without touching the items they should stay in the same place.

**Screenshots**
Optional, but may help us solve your issue faster.
Before:
![2019-12-13_20 39 23](https://user-images.githubusercontent.com/58871551/70843617-29428700-1dea-11ea-93fa-c086031e5f49.png)

In Inventory:
![2019-12-13_20 39 33](https://user-images.githubusercontent.com/58871551/70843622-3790a300-1dea-11ea-9bef-04731cc2159b.png)

After:
![2019-12-13_20 39 40](https://user-images.githubusercontent.com/58871551/70843625-3eb7b100-1dea-11ea-8529-61a64f07c1b5.png)

With Another Box (Before):
![2019-12-13_20 42 07](https://user-images.githubusercontent.com/58871551/70843632-54c57180-1dea-11ea-91bc-b939fe56d889.png)

Then I move the heart of the sea to the right slot:
![2019-12-13_20 42 11](https://user-images.githubusercontent.com/58871551/70843636-5f800680-1dea-11ea-8e9c-f435ce0d2d39.png)

And when I break it and pick it back up, the heart has moved back to its original postition
![2019-12-13_20 42 18](https://user-images.githubusercontent.com/58871551/70843638-6dce2280-1dea-11ea-85e0-af64d55fa869.png)

I'm still struggling to figure out exactly whats going on here, but thought it would be beneficial to have it on record.

- Androiddude73

**Comment by thecenters** [comment]
This is a legacy issue with the server that I don't think can be fixed. I can explain what's going on with it. When the shulker is placed into your inventory it's added to our per world inventory plugin. I don't think it saves specific slots inside of the shulker and so the order gets messed up.

I will see what I can do about this, but I can't guarantee a fix.

**Comment by thecenters** [comment]
Unfortunately there isn't a fix for this.
