### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by aliedyne202** [theoutpostmc/issue-tracker#23]
**Describe the bug**
Item stucked inside of hoppers. Hoppers wont let the item transferred into another hopper..

**To Reproduce**
It happened when 3 hoppers connected into 1.
And also when i tries to use item sorter. Item will stucked before they go to first hopper in sorting system
**Expected behavior**
I just need the hoppers working correcty just like offline world

**Comment by thecenters** [comment]
Closed as duplicate. There is a report about this already.
