### ISSUE TITLE
[BUG] Auto sorters dont work

### ISSUE THREAD

**Issue by DarkAgent1** [theoutpostmc/issue-tracker#25]
Auto sorting hoppers cant take the items for some reason

If you have a line of hoppers going somewhere and then Auto sorting hoppers below them items just go throught the first line.

Items should be going through the first line of hoppers but if there is a hopper bellow and its sorting lets say "prismarine shards" when that item goes throught the first line it should get sucked up by the auto sorting hopper.

**Screenshots**
Optional, but may help us solve your issue faster.

**Comment by thecenters** [comment]
Closed as duplicate. There is a report about this already.
