### ISSUE TITLE
/sethome bug for vp

### ISSUE THREAD

**Issue by airaaaa** [theoutpostmc/issue-tracker#3]
A clear and complete description of what the bug is: Bossernatortr1 mentioned that a new player (Two_Lego_Boys) that has only 1 sethome currently in Vanilla Plus did set a home beforehand and now wanted to replace that sethome with a new one. So basically he needs to delete the old home in order to re-do a new home which now he cant. Using the /homes command doesn't show up the menu where u can view and delete your home. Also to note that other players that has more than one home is able to get the home menu from the command. 

1. Use the /homes command

Expected behavior:
The home command menu is suppose to show up for all players including those who only have one sethome to delete/view all their sethomes.

**Comment by thecenters** [comment]
Researching this it appears that Two_Lego_Boys was able to create a home properly inside of his home.
