### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by orangepeelss** [theoutpostmc/issue-tracker#9]
**Describe the bug**
In the creative server the /plots merge feature is disabled

**To Reproduce**
1. Go to creative server
2. Do /claim on 2 adjacent plots and then stand in one and face the other and do /plots merge
3. Then:  [Creative] You do not own any adjacent plots in the specified direction or are not allowed to merge to the required size.

**Expected behavior**
The plots should merge into 1 large rectangular plot

**Screenshots**
![2020-01-01_17 25 45](https://user-images.githubusercontent.com/59424107/71648032-3998a400-2cbc-11ea-8549-72832bbb1f29.png)

**Comment by thecenters** [comment]
This is fixed
